Repository konentung/OnlineProgrammingPlatform, pull requests merged in 2025-01, with the labels that each got.

#31 CODINGPJ-33 postgreSQL
  OnlineProgrammingPlatform/settings.py
  posts/admin.py
  posts/models.py
  requirements.txt
Labels: feature

#32 CODINGPJ-28 user_dashboard頁面
  templates/user_dashboard.html
Labels: feature

#15 CODINGPJ-2 detail頁面
  templates/questions/question_detail.html
Labels: feature

#33 Develop
  OnlineProgrammingPlatform/settings.py
  posts/admin.py
  posts/models.py
  posts/views.py
  requirements.txt
  templates/questions/question_detail.html
  templates/user_dashboard.html
Labels: feature

#34 CODINGPJ-34 設定CSRF_TOKEN
  OnlineProgrammingPlatform/settings.py
Labels: env, feature

#35 Develop
  OnlineProgrammingPlatform/settings.py
Labels: env, feature

#36 rm cache
  OnlineProgrammingPlatform/settings.py
Labels: feature

#40 CODINGPJ-30 所有頁面欄位重整
  OnlineProgrammingPlatform/urls.py
  posts/forms.py
  posts/models.py
  posts/views.py
  static/js/answer_submit.js
  static/js/codespace.js
  static/js/question_card.js
  static/js/question_submit.js
  static/js/question_update.js
  static/js/ranking.js
  static/js/review_submit.js
  templates/index.html
  templates/questions/question_answer.html
  templates/questions/question_assignment_list.html
  templates/questions/question_create.html
  templates/questions/question_history_list.html
  templates/questions/question_peer_assessment.html
  templates/questions/question_review.html
  templates/questions/question_update.html
  templates/questions/ranking.html
  templates/questions/teacher_dashboard.html
  templates/questions/user_question_history_list.html
  templates/user_dashboard.html
Labels: feature

#38 CODINGPJ-6 question_history頁面
  templates/questions/question_history_list.html
  templates/questions/user_question_history_list.html
Labels: feature

#39 CODINGPJ-26 ranking、AccountBase頁面
  staticfiles/css/accounts.css
  templates/questions/ranking.html
Labels: feature

#30 CODINGPJ-27 maintenance、close頁面
  templates/close.html
  templates/maintenance.html
Labels: feature

#41 CODINGPJ-34 靜態檔案處理
  staticfiles/js/answer_submit.js
  staticfiles/js/codespace.js
  staticfiles/js/question_card.js
  staticfiles/js/question_submit.js
  staticfiles/js/question_update.js
  staticfiles/js/ranking.js
  staticfiles/js/review_submit.js
Labels: feature

#42 CODINGPJ-32 base頁面重設
  templates/base.html
Labels: feature

#44 CODINGPJ-29 answer頁面顯示問題
  templates/questions/question_answer.html
Labels: bugfix
